CREATE OR REPLACE VIEW wpaef_xtr_vw_postmeta_referenced AS 
select sql_cache p.ID AS id,p.post_title AS post_title,p.post_type AS post_type,p.post_author AS post_author,m.meta_id AS meta_id,m.post_id AS post_id,m.meta_key AS meta_key,m.meta_value AS meta_value,if((m.meta_key in ('_cp__exh_source_entity','_cp__exh_parent_exhibition','_cp__exh_info_source','_cp__exh_artwork_author','_cp__exh_supporter_entity','_cp__exh_funding_entity','_cp__exh_curator','_cp__exh_catalog','_cp__exh_museography','_cp__exh_art_collector','_cp__ent_parent_entity','_cp__peo_person_relation','_cp__boo_paper_author','_cp__boo_sponsorship')),if((locate(':',m.meta_value) > 0),cast(substring_index(m.meta_value,':',1) as unsigned),NULL),NULL) AS n_ref_id,if((m.meta_key in ('_cp__exh_source_entity','_cp__exh_parent_exhibition','_cp__exh_info_source','_cp__exh_artwork_author','_cp__exh_supporter_entity','_cp__exh_funding_entity','_cp__exh_curator','_cp__exh_catalog','_cp__exh_museography','_cp__exh_art_collector','_cp__ent_parent_entity','_cp__peo_person_relation','_cp__boo_paper_author','_cp__boo_sponsorship')),if((locate(':',m.meta_value) > 0),(select wpaef_posts.post_type from wpaef_posts where (wpaef_posts.ID = cast(substring_index(m.meta_value,':',1) as unsigned))),NULL),NULL) AS s_typ_ref_id,if((m.meta_key in ('_cp__ent_town','_cp__exh_exhibition_town','_cp__boo_publishing_place','_cp__exh_exhibition_town','_cp__com_company_headquarter_place','_cp__boo_publishing_place')),trim(substring_index(substring_index(m.meta_value,';',-(1)),';',1)),if((m.meta_key = '_cp__peo_country'),m.meta_key,NULL)) AS s_country,if((m.meta_key in ('_cp__ent_town','_cp__exh_exhibition_town','_cp__boo_publishing_place','_cp__exh_exhibition_town','_cp__com_company_headquarter_place','_cp__boo_publishing_place')),trim(substring_index(substring_index(m.meta_value,';',-(2)),';',1)),NULL) AS s_region,if((m.meta_key in ('_cp__ent_town','_cp__exh_exhibition_town','_cp__boo_publishing_place','_cp__exh_exhibition_town','_cp__com_company_headquarter_place','_cp__boo_publishing_place')),trim(substring_index(m.meta_value,';',1)),NULL) AS s_town,if((m.meta_key in ('_cp__boo_publishing_date','_cp__peo_birth_date','_cp__peo_death_date','_cp__exh_exhibition_start_date','_cp__exh_exhibition_end_date')),year(str_to_date(m.meta_value,'%Y-%m-%d')),NULL) AS n_year,if((m.meta_key in ('_cp__boo_publishing_date','_cp__peo_birth_date','_cp__peo_death_date','_cp__exh_exhibition_start_date','_cp__exh_exhibition_end_date')),month(str_to_date(m.meta_value,'%Y-%m-%d')),NULL) AS n_month from (wpaef_postmeta m join wpaef_posts p on((p.ID = m.post_id))) where ((p.post_type in ('entity','person','book','company','exhibition')) and (p.post_status = 'publish') and (m.meta_key like '_cp__%'));

CREATE OR REPLACE VIEW wpaef_xtr_vw_post_taxonomies AS 
select sql_cache p.ID AS ID,p.post_title AS post_title,p.post_status AS post_status,p.post_type AS post_type,tt.taxonomy AS taxonomy,t.name AS term,t.term_id AS term_id from (wpaef_posts p join ((wpaef_term_relationships tr join wpaef_term_taxonomy tt on((tr.term_taxonomy_id = tt.term_taxonomy_id))) join wpaef_terms t on((tt.term_id = t.term_id))) on((p.ID = tr.object_id))) where (tt.taxonomy like 'tax_%');

CREATE OR REPLACE VIEW wpaef_xtr_vw_post_grouped_metas AS 
select sql_cache p.ID AS ID,p.post_title AS post_title,p.post_status AS post_status,p.post_type AS post_type,pm.meta_key AS meta_key,group_concat(distinct pm.meta_value order by pm.meta_value ASC separator ';') AS metas from (wpaef_posts p join wpaef_postmeta pm on((p.ID = pm.post_id))) where ((p.post_type in ('entity','person','book','company','exhibition')) and (p.post_status = 'publish') and (pm.meta_key like '_cp__%')) group by p.ID,p.post_title,p.post_status,p.post_type,pm.meta_key;

CREATE OR REPLACE VIEW wpaef_xtr_vw_post_grouped_taxonomies AS 
select sql_cache p.ID AS ID,p.post_title AS post_title,p.post_status AS post_status,p.post_type AS post_type,tt.taxonomy AS taxonomy,group_concat(distinct t.name order by t.name ASC separator ';') AS terms from (wpaef_posts p join ((wpaef_term_relationships tr join wpaef_term_taxonomy tt on((tr.term_taxonomy_id = tt.term_taxonomy_id))) join wpaef_terms t on((tt.term_id = t.term_id))) on((p.ID = tr.object_id))) where ((p.post_type in ('entity','person','book','company','exhibition')) and (p.post_status = 'publish') and (tt.taxonomy like 'tax_%')) group by p.ID,p.post_title,p.post_status,p.post_type,tt.taxonomy;